- name: Install SDK Required
  pip:
    name: docker

- name: Create a temporary working directory
  tempfile:
    state: directory
    prefix: nvidia_driver_build
  register: build_dir

- name: Checkout nvidia/driver upstream
  git:
    repo: https://gitlab.com/nvidia/container-images/driver.git
    dest: "{{ build_dir.path }}"
    depth: "1"

- name: Build docker image
  community.docker.docker_image:
    build:
      path: "{{ build_dir.path }}/fedora"
      args:
        FEDORA_VERSION: "{{ FEDORA_VERSION }}"
        DRIVER_VERSION: "{{ NVIDIA_DRIVER_VERSION }}"
    name: "{{ HARBOR_TAG }}"
    source: build
    push: yes

- name: Clear working dir
  file:
    path: "{{ build_dir.path }}"
    state: absent
