---
# We need a unique identifier so use a service version number we should bump
release_version: "1-0" # Magnum will replace . with - breaking things
cluster_name: "jupyter-{{ release_version }}"
num_masters: 2
num_workers: 1
max_worker_nodes: 20
max_gpu_nodes: 0

keypair_name: "david_fair"

master_flavor: "c3.small"
worker_flavor: "c3.medium"
gpu_flavor: "g-p4000.x1"

mirror_url: harbor.stfc.ac.uk/magnum_mirror/

docker_volume_size_gb: 10
# Magnum deploys 1.0 by default, we need 1.19+ to be Node Group aware
cluster_autoscaler_version: "v1.19.0"
kube_tag: "v1.16.13"
# Because the official mirror (which we mirror from) uses vx.y.z instead of x.y.z that coreos uses
etcd_tag: "v3.3.25"

# Kubernetes specific
# We need to enable the priority plugin manually, the list of default plugins + 'Priority' is from:
# https://opendev.org/openstack/magnum/src/branch/stable/ussuri/magnum/drivers/k8s_fedora_coreos_v1/templates/kubecluster.yaml
admission_plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority"
# Is this best practice, no. But until https://github.com/NVIDIA/gpu-operator/issues/26
# is merged we have to use their hardcoded taint, despite the fact only the driver
# should be using this
gpu_taint: "nvidia.com/gpu=present:NoSchedule"
kubectl_port: 6443
