---
- name: Deploy Magnum Cluster + LB Access
  include_tasks: deploy_magnum_cluster.yml

- name: Enable GPU Support on Magnum Cluster if num_gpu > 0
  include_tasks: enable_gpu.yml
  when: "max_gpu_nodes != 0"
